---
spring:
    profiles:
        active: local

    application:
        name: cloud-spring-example

    main:
        log-startup-info: false
        banner-mode: off

    shell:
        interactive:
          enabled: true

logging:
    level:
        org.incendo: info
